language: python
services:
  -docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: dry-bayou-38045
  api_key: ${HEROKU_API_KEY}
